// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaZPBIpyoW1qGFRbrAf4wCTQZfKqZ4g3E',
    appId: '1:304479613215:web:c264ee94f364325a99c02a',
    messagingSenderId: '304479613215',
    projectId: 'flutter-app-a6671',
    authDomain: 'flutter-app-a6671.firebaseapp.com',
    storageBucket: 'flutter-app-a6671.appspot.com',
    measurementId: 'G-MF32B41BBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC1B4teMQy80t_ZbWcqYtCQST0xZ7457o',
    appId: '1:304479613215:android:48eb076b970ff1b299c02a',
    messagingSenderId: '304479613215',
    projectId: 'flutter-app-a6671',
    storageBucket: 'flutter-app-a6671.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDRjrP768xVGjxGasmOdouvI3nd17m5NA',
    appId: '1:304479613215:ios:1103b12b7748e2ce99c02a',
    messagingSenderId: '304479613215',
    projectId: 'flutter-app-a6671',
    storageBucket: 'flutter-app-a6671.appspot.com',
    iosBundleId: 'com.example.flutterGoogle1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDRjrP768xVGjxGasmOdouvI3nd17m5NA',
    appId: '1:304479613215:ios:df3593effcb0bbc099c02a',
    messagingSenderId: '304479613215',
    projectId: 'flutter-app-a6671',
    storageBucket: 'flutter-app-a6671.appspot.com',
    iosClientId: '304479613215-ivtl2fubriblq3jibebottmkhhcp99rq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication.RunnerTests',
  );
}
